### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LordRampantHump** [fastogt/iptv#1]
does this transcode? Can it take hls input for hls output?

**Comment by topilski** [comment]
Yes, we support transcode

**Comment by topilski** [comment]
Here some example for starting transcode stream: https://github.com/fastogt/iptv/blob/master/clients/client.py

**Comment by LordRampantHump** [comment]
wow fast reply. This might be just what im looking for then. Can you advise how to install. Im new to linux but if you point me in the right direction ill get the job done!

**Comment by topilski** [comment]
Oy, sure, let's start from this script https://github.com/fastogt/iptv/blob/master/build/build_env.py

**Comment by LordRampantHump** [comment]
well buddy i gave this a try, it seemed to send me in a whirlwind back installing dependencies.

File "build_env.py", line 8, in <module>  from pyfastogt import system_info, utils mportError: No module named 'pyfastogt' 

so i tried to install pyfastogt and learned it is dependent on common, so tried to install common 

I tried to install common but i got stuck at

-- CMAKE_INSTALL_PREFIX: /usr/local
CMake Error at CMakeLists.txt:56 (INCLUDE):
  include could not find load file:

    config


CMake Error at CMakeLists.txt:57 (DEFINE_DEFAULT_DEFINITIONS):
  Unknown CMake command "DEFINE_DEFAULT_DEFINITIONS".

**Comment by topilski** [comment]
git submodule update --init --recursive and after that try again

**Comment by topilski** [comment]
Yes

**Comment by topilski** [comment]
Sorry for this, need to find to write wiki

**Comment by LordRampantHump** [comment]
dont be sorry buddy, i need to learn more! Did you get my email i sent to **opilsk*@gmail.com

**Comment by topilski** [comment]
Yes, received your email

**Comment by LordRampantHump** [comment]
do you think you could do that for me?

**Comment by LordRampantHump** [comment]
hey mate i sent you the details, thanks again
