### ISSUE TITLE
MAG Portal

### ISSUE THREAD

**Issue by LiamKenyon** [fastogt/iptv#3]
Does the platform support MAG boxes via stalker portal?

**Comment by topilski** [comment]
Sorry, i don't know about stalker portal, can you give some description.

**Comment by topilski** [comment]
Thank you @LiamKenyon , I need to do some research.

**Comment by LiamKenyon** [comment]
See the attached link this is the stalker portal with Xtream Codes (old version) may help you as a starting point

https://we.tl/t-ozXrbQKW4h - This was also the stalker portal released by Informir until they made it un opensource.

**Comment by topilski** [comment]
Hi @LiamKenyon , yesterday I tried to install stalker on other machines but without success, I think this repo is not supported anymore.

**Comment by topilski** [comment]
I think we don't want to support Xtream Codes and Stalker portal, we have own players.
