### ISSUE TITLE
no service

### ISSUE THREAD

**Issue by penfolduk** [fastogt/iptv#5]
root@flussonic:~/iptv/build# PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig ./build.py release 66ad5b2ea5e2451f914fea2f4e9c59ada957850d2835ad1986d4e1c4bc30f0c5
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- PROJECT_VERSION: 1.1.0.0
-- CMAKE_INSTALL_PREFIX: /usr/local
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- PLATFORM_ARCH_NAME:x86_64
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- CMAKE_HOST_SYSTEM_PROCESSOR: x86_64
-- CMAKE_SYSTEM: Linux-4.15.0-20-generic
-- CMAKE_CXX_COMPILER_ID: GNU
-- CMAKE_USE_PTHREADS_INIT : 1
-- CMAKE_BUILD_TYPE: RELEASE
-- BZIP2_USE_STATIC: OFF
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIRS)
-- ZLIB_USE_STATIC: OFF
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- LZ4_USE_STATIC: OFF
-- Could NOT find lz4 (missing:  LZ4_LIBRARIES LZ4_INCLUDE_DIRS)
-- SNAPPY_USE_STATIC: OFF
-- Could NOT find Snappy (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIRS)
-- iptv_cloud git version: 81189e7
-- LIBEV_USE_STATIC: OFF
-- Found LibEv: /usr/local/lib/libev.a (found version "4.24")
-- Found common: /usr/local/lib/libcommon_ev.a;/usr/local/lib/libev.a;/usr/local/lib/libcommon.a
-- JSONC_USE_STATIC: OFF
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found JSONC: /usr/local/lib/libjson-c.a
CMake Error at src/utils/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.3.0 or higher is required.  You are running version 3.1.0

-- Configuring incomplete, errors occurred!
See also "/root/iptv/build_cmake_release/CMakeFiles/CMakeOutput.log".
See also "/root/iptv/build_cmake_release/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory

**Comment by topilski** [comment]
Hey, let's check

**Comment by topilski** [comment]
@penfolduk fixed, please update repo., Thank you for the issue.
