### ISSUE TITLE
Error during ./build_env.py

### ISSUE THREAD

**Issue by electron64** [fastogt/iptv#7]
hello i get an error during the install on ubuntu 18.04.
Any idea how to solve it please?

`Check plugin mfxh264enc, failed return code: 255
Check plugin mfxvpp, failed return code: 255
Check plugin mfxh264dec, failed return code: 255`

**Comment by topilski** [comment]
It is ok, mfx additional plugins, for mfx based devices.

**Comment by electron64** [comment]
Ok thank you for your fast answer.
