### ISSUE TITLE
./build

### ISSUE THREAD

**Issue by gear259** [fastogt/iptv#9]
please review:

Heading: 'Build enviroment:' 
Issue: spelling error
Solution: change to 'Build Environment'

Code:
./build_env.py
Issue: user will be in the root directory following previous instruction and will not know where build.py is located.
Solution:  Change ./build_env.py to ./iptv/build/build_env.py

**Comment by topilski** [comment]
https://github.com/fastogt/iptv/wiki/Build according wiki cd build

**Comment by gear259** [comment]
please refer to your own wiki before replying.  The instructions go from cd /build back to cd ../ at step 3 (Install FastoGT....)
user then needs to cd /build
or you could make it much simpler by not cd all over the place FULL PATH ./iptv/build/build_env.py
